### ISSUE TITLE
Packagist package requires symfony/validator: 2.1.x-dev

### ISSUE THREAD

**Issue by DSpeichert** [nucleus-be/zimbra#2]
Requirement ```symfony/validator: 2.1.x-dev``` - this version does not exist.

**Comment by DSpeichert** [comment]
Can you update composer package as well?
https://packagist.org/packages/nucleusbe/zimbra still shows old dependency.

**Comment by chrisramakers** [comment]
Seems packagist was a little sluggy with updating the repo, i've manually updated it.

Cheers
Chris
